### ISSUE TITLE
bug found

### ISSUE THREAD

**Issue by mithuncoder** [poggersbutnot/pbn_obfuscator#1]
def nxdrm(*pvbu):
            xadvx = []
            for tcza in pvbu:
                xadvx.append(getattr(__import__("builtins"), "chr")(tcza))
            return ''.join(xadvx)
getattr(__import__("builtins"), "exec")

You are using javascript hexadecimal string Escaper/Unescaper.

i decrypt that codes via online.if decrypted, we change print instead of exec after we got the source code.

please fix this..otherwise your obfuscator really advanced.cant decrypt the hexlify eval code

**Comment by poggersbutnot** [comment]
You can decrypt ANYTHING. I am working on a new obfuscator that could possibly fix this.
